// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEAp9wa8I-ILDn7dNr8Ji4vhVBHl9A-KQ',
    appId: '1:850082911611:web:4c227cc9823e7a01a219de',
    messagingSenderId: '850082911611',
    projectId: 'fksarajevo-shop-dev',
    authDomain: 'fksarajevo-shop-dev.firebaseapp.com',
    storageBucket: 'fksarajevo-shop-dev.firebasestorage.app',
    measurementId: 'G-Z4D4E7LP31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjnslhH-s63gsGYAlGxRP17KXuNu0DrEo',
    appId: '1:850082911611:android:42594a68cf31e95ea219de',
    messagingSenderId: '850082911611',
    projectId: 'fksarajevo-shop-dev',
    storageBucket: 'fksarajevo-shop-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWgXbpjUbHLwp6m3ubpg3W-qZbKIUIJis',
    appId: '1:850082911611:ios:478ca43f122e7e04a219de',
    messagingSenderId: '850082911611',
    projectId: 'fksarajevo-shop-dev',
    storageBucket: 'fksarajevo-shop-dev.firebasestorage.app',
    iosBundleId: 'com.example.fksarajevoshop.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWgXbpjUbHLwp6m3ubpg3W-qZbKIUIJis',
    appId: '1:850082911611:ios:79423335b2968d63a219de',
    messagingSenderId: '850082911611',
    projectId: 'fksarajevo-shop-dev',
    storageBucket: 'fksarajevo-shop-dev.firebasestorage.app',
    iosBundleId: 'com.example.fksarajevoShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEAp9wa8I-ILDn7dNr8Ji4vhVBHl9A-KQ',
    appId: '1:850082911611:web:528971769ef0ff2fa219de',
    messagingSenderId: '850082911611',
    projectId: 'fksarajevo-shop-dev',
    authDomain: 'fksarajevo-shop-dev.firebaseapp.com',
    storageBucket: 'fksarajevo-shop-dev.firebasestorage.app',
    measurementId: 'G-YDN88K4MVL',
  );
}
