// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvYmSzOHfCGkrdhPFLhkg-VzeWkVD77_4',
    appId: '1:514981421221:web:0ef9864500ace0f12aad4c',
    messagingSenderId: '514981421221',
    projectId: 'fksarajevo-shop-prod',
    authDomain: 'fksarajevo-shop-prod.firebaseapp.com',
    storageBucket: 'fksarajevo-shop-prod.firebasestorage.app',
    measurementId: 'G-57WB4PCMLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa7WQdwSQTKlYCMmfko1R2GaAa0RngFsw',
    appId: '1:514981421221:android:5ca5e6b3317218f02aad4c',
    messagingSenderId: '514981421221',
    projectId: 'fksarajevo-shop-prod',
    storageBucket: 'fksarajevo-shop-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUNLR3sNBKb5jsSRulqVmP15PhnphaPIE',
    appId: '1:514981421221:ios:7483bad414f4d2742aad4c',
    messagingSenderId: '514981421221',
    projectId: 'fksarajevo-shop-prod',
    storageBucket: 'fksarajevo-shop-prod.firebasestorage.app',
    iosBundleId: 'com.example.fksarajevoshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUNLR3sNBKb5jsSRulqVmP15PhnphaPIE',
    appId: '1:514981421221:ios:cbc5534211210e5f2aad4c',
    messagingSenderId: '514981421221',
    projectId: 'fksarajevo-shop-prod',
    storageBucket: 'fksarajevo-shop-prod.firebasestorage.app',
    iosBundleId: 'com.example.fksarajevoShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvYmSzOHfCGkrdhPFLhkg-VzeWkVD77_4',
    appId: '1:514981421221:web:681a1ea4c3454acd2aad4c',
    messagingSenderId: '514981421221',
    projectId: 'fksarajevo-shop-prod',
    authDomain: 'fksarajevo-shop-prod.firebaseapp.com',
    storageBucket: 'fksarajevo-shop-prod.firebasestorage.app',
    measurementId: 'G-3VQVK6N7J3',
  );
}
